{% set name = "radian" %}
{% set version = "0.7.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/radian-{{ version }}.tar.gz
  sha256: dfbd6a649aa7c2e3546ed83483193f95a89fa85351cafedcaeb13a0acfb1e728

build:
  number: 0
  noarch: python
  entry_points:
    - radian = radian:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=61.0
    - wheel
  run:
    - pygments >=2.5.0
    - python >={{ python_min }}
    - prompt_toolkit >=3.0.41,<3.1
    - rchitect >=0.5.1,<0.6.0

test:
  imports:
    - radian
    - radian.latex
  commands:
    - pip check
    - radian --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/randy3k/radian
  summary: A 21 century R console
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - randy3k
    - jdblischak
