{% set name = "radian" %}
{% set version = "0.6.15" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/radian-{{ version }}.tar.gz
  sha256: abbd92907012deee0b46429d69e52193e4ae2b0183efaeb96b425d89f9e9db7f

build:
  number: 0
  noarch: python
  entry_points:
    - radian = radian:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest-runner
    - python {{ python_min }}
  run:
    - pygments >=2.5.0
    - python >={{ python_min }}
    - prompt_toolkit >=3.0.41,<3.1
    - rchitect >=0.4.8,<0.5.0

test:
  imports:
    - radian
    - radian.latex
  commands:
    - pip check
    - radian --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/randy3k/radian
  summary: A 21 century R console
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - randy3k
    - jdblischak
