{% set name = "radian" %}
{% set version = "0.6.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/radian-{{ version }}.tar.gz
  sha256: 9aa6e1afc619deee99ae16dc38237f1cba52fbbd7e70464f054ce50edb00e8ef

build:
  number: 0
  noarch: python
  entry_points:
    - radian = radian:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest-runner
    - python !=3.0,!=3.1,!=3.2,!=3.3,!=3.4
  run:
    - pygments >=2.5.0
    - python !=3.0,!=3.1,!=3.2,!=3.3,!=3.4
    - prompt_toolkit >=3.0.15,<3.1
    - rchitect >=0.3.36,<0.4.0
    - six >=1.9.0

test:
  imports:
    - radian
    - radian.latex
  commands:
    - pip check
    - radian --help
  requires:
    - pip

about:
  home: https://github.com/randy3k/radian
  summary: A 21 century R console
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - randy3k
    - jdblischak
